# Generated by Django 3.1.1 on 2021-07-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('cert_id', models.CharField(max_length=50, unique=True)),
                ('event', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2021)),
            ],
        ),
    ]
