# Generated by Django 3.1.1 on 2021-07-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificateVerification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('father_name', models.CharField(blank=True, max_length=127, null=True)),
                ('membership_num', models.CharField(max_length=63, unique=True)),
                ('role', models.CharField(max_length=127)),
                ('contributions', models.TextField()),
                ('year', models.CharField(max_length=10)),
                ('certificate_num', models.CharField(max_length=63)),
            ],
        ),
    ]
