# Generated by Django 3.1.1 on 2021-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificateVerification', '0003_auto_20210718_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contributions',
            field=models.CharField(max_length=511),
        ),
    ]
