# Generated by Django 3.1.1 on 2024-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificateVerification', '0005_auto_20210718_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='member',
            name='certificate_num',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_num',
            field=models.CharField(max_length=63),
        ),
    ]
